# Generated by Django 4.0 on 2021-12-12 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0003_chat'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='chat',
            new_name='chatdata',
        ),
    ]
