# Generated by Django 4.0 on 2021-12-12 06:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0005_remove_chatdata_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatdata',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
