# Generated by Django 4.0 on 2021-12-31 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0006_chatdata_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='password',
            field=models.CharField(default='sabarish', max_length=100),
            preserve_default=False,
        ),
    ]
